# Generated by Django 3.0.5 on 2020-09-01 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0002_auto_20200901_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientes',
            name='recetas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receta', to='recetas.Recetas'),
        ),
    ]
