# Generated by Django 3.0.5 on 2020-08-20 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0002_auto_20200714_1200'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productos',
            options={'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterField(
            model_name='recetas',
            name='ingredientes',
            field=models.ManyToManyField(blank=True, null=True, related_name='ingredientes', to='recetas.Ingredientes'),
        ),
    ]
