# Generated by Django 3.0.5 on 2020-09-01 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0003_auto_20200901_1052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredientes',
            name='recetas',
        ),
        migrations.AlterField(
            model_name='recetas',
            name='ingredientes',
            field=models.ManyToManyField(blank=True, null=True, related_name='ingredientes', to='recetas.Ingredientes'),
        ),
    ]
